import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';

// Ensure 'firstapp' matches the name in your pubspec.yaml
import 'package:firstapp/core/platform/network_info.dart';
import 'package:firstapp/features/product/data/datasources/product_local_data_source.dart';
import 'package:firstapp/features/product/data/datasources/product_remote_data_source.dart';
import 'package:firstapp/features/product/data/models/product_model.dart';
import 'package:firstapp/features/product/data/repositories/product_repository_impl.dart';
// This file is generated by build_runner.
import 'product_repository_impl_test.mocks.dart';

@GenerateMocks([ProductRemoteDataSource, ProductLocalDataSource, NetworkInfo])
void main() {
  late ProductRepositoryImpl repository;
  late MockProductRemoteDataSource mockRemoteDataSource;
  late MockProductLocalDataSource mockLocalDataSource;
  late MockNetworkInfo mockNetworkInfo;

  setUp(() {
    mockRemoteDataSource = MockProductRemoteDataSource();
    mockLocalDataSource = MockProductLocalDataSource();
    mockNetworkInfo = MockNetworkInfo();
    repository = ProductRepositoryImpl(
      remoteDataSource: mockRemoteDataSource,
      localDataSource: mockLocalDataSource,
      networkInfo: mockNetworkInfo,
    );
  });

  const tProductModel = ProductModel(
    id: '1',
    name: 'Test Shoe',
    description: 'Description',
    imageUrl: 'url',
    price: 100,
    size: 42,
    category: 'Sports',
  );

  const tProductModelList = [tProductModel];

  group('getAllProducts', () {
    test('should check if the device is online', () async {
      // arrange
      when(mockNetworkInfo.isConnected).thenAnswer((_) async => true);
      when(
        mockRemoteDataSource.fetchAllProducts(),
      ).thenAnswer((_) async => tProductModelList);
      when(
        mockLocalDataSource.cacheProducts(any),
      ).thenAnswer((_) async => Future.value());

      // act
      await repository.getAllProducts();

      // assert
      verify(mockNetworkInfo.isConnected);
    });

    group('device is online', () {
      test('should return remote data and cache it locally', () async {
        // arrange
        when(mockNetworkInfo.isConnected).thenAnswer((_) async => true);
        when(
          mockRemoteDataSource.fetchAllProducts(),
        ).thenAnswer((_) async => tProductModelList);
        when(
          mockLocalDataSource.cacheProducts(any),
        ).thenAnswer((_) async => Future.value());

        // act
        final result = await repository.getAllProducts();

        // assert
        expect(result, equals(tProductModelList));
        verify(mockRemoteDataSource.fetchAllProducts());
        verify(mockLocalDataSource.cacheProducts(tProductModelList));
      });
    });

    group('device is offline', () {
      test(
        'should return last locally cached data when device is offline',
        () async {
          // 1. Arrange
          when(mockNetworkInfo.isConnected).thenAnswer((_) async => false);
          when(
            mockLocalDataSource.getLastProducts(),
          ).thenAnswer((_) async => tProductModelList);

          // 2. Act
          final result = await repository.getAllProducts();

          // 3. Assert
          // This ensures the remote data source was NOT called
          verifyNever(mockRemoteDataSource.fetchAllProducts());

          // This ensures the local data source WAS called
          verify(mockLocalDataSource.getLastProducts());

          expect(result, equals(tProductModelList));
        },
      );
    });
  });

  group('createProduct', () {
    test('should add to remote and local when online', () async {
      // arrange
      when(mockNetworkInfo.isConnected).thenAnswer((_) async => true);
      when(
        mockRemoteDataSource.addProduct(any),
      ).thenAnswer((_) async => Future.value());
      when(
        mockLocalDataSource.cacheProduct(any),
      ).thenAnswer((_) async => Future.value());

      // act
      await repository.createProduct(tProductModel);

      // assert
      verify(mockRemoteDataSource.addProduct(tProductModel));
      verify(mockLocalDataSource.cacheProduct(tProductModel));
    });
  });
}
